spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reviewdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

gemini:
  api:
    key: ${GEMINI_API_KEY}

github:
  token: ${GITHUB_TOKEN}

server:
  port: 8080  # You can change it if you want

